### ISSUE TITLE
Struggles to find EXEC_FOLDER

### ISSUE THREAD

**Issue by haarp** [RitwickVerma/Gesture-Manager-X#3]
When main.py is symlinked in `/usr/bin`, the app assumes that as EXEC_FOLDER, which is wrong. To fix,

`EXEC_FOLDER = os.path.realpath(os.path.dirname(__file__)) + "/"` needs to be replaced with `EXEC_FOLDER = os.path.dirname(os.path.realpath(__file__)) + /`

Thanks!

**Comment by RitwickVerma** [comment]
Hey @haarp, Thanks for pointing it out. Changed it in cf56062f23d76808a1e4ff316c2f84d3c465da5a
